KARUT: list = []

KARUT.append("Colorful Mess")
KARUT.append("Funky Road")
KARUT.append("Connected Sky")
KARUT.append("Shooting Stars")
KARUT.append("Barrier")
KARUT.append("Step by Step")
KARUT.append("Mechanical JUNGLE")
KARUT.append("Virtual Storm")
KARUT.append("Tech N Tech")
KARUT.append("Fade Out")
KARUT.append("Plug and Play")
KARUT.append("Alert")
KARUT.append("CrossFire")
KARUT.append("Water Drop")
KARUT.append("Neo City Dive")
KARUT.append("Interface")
KARUT.append("Glitch Street")
KARUT.append("KIRISAME")
KARUT.append("Out of Control (All)")
KARUT.append("Out of Control 03 (Chorus)")
KARUT.append("Out of Control 01 (Intro)")
KARUT.append("Out of Control 02 (Verse)")
KARUT.append("Mechanical JUNGLE (Hi-Tech Full On Mix)")
KARUT.append("Hue")
KARUT.append("Accelerator")
KARUT.append("Golden Shangri-la")
KARUT.append("Someday, sometime")
KARUT.append("Black Suit")
KARUT.append("Denshi Toujou!")
KARUT.append("Kaiten Screw!!!")
KARUT.append("Tech N Tech Hard Arrange")
KARUT.append("Alert Hard Arrange")
KARUT.append("CrossFire Hard Arrange")
KARUT.append("Fever Time")
KARUT.append("Summer Bounce Hard Arrange")
KARUT.append("Library of Omen (All)")
KARUT.append("Library of Omen (8bit)")
KARUT.append("Library of Omen (Chorus)")
KARUT.append("Library of Omen (Verse)")
KARUT.append("Oriental Drop")
KARUT.append("The Dragon Express")
KARUT.append("Jackpot 777")
KARUT.append("Oxygen Destroyer")
KARUT.append("Undefined Behavior")