Mitsukiyo: list = []

Mitsukiyo.append("Constant Moderato")
Mitsukiyo.append("Luminous memory")
Mitsukiyo.append("Mischievous Step")
Mitsukiyo.append("Lovely Picnic")
Mitsukiyo.append("Unwelcome School")
Mitsukiyo.append("Shady Girls")
Mitsukiyo.append("Midsummer cat")
Mitsukiyo.append("Romantic Smile")
Mitsukiyo.append("Honey Jam")
Mitsukiyo.append("MX Adventure")
Mitsukiyo.append("Irasshaimase")
Mitsukiyo.append("Party time")
Mitsukiyo.append("Endless Carnival (All)")
Mitsukiyo.append("Endless Carnival 8-Bit Arrange")
Mitsukiyo.append("Endless Carnival 03 (Chorus)")
Mitsukiyo.append("Endless Carnival 01 (Intro)")
Mitsukiyo.append("Endless Carnival 02 (Verse)")
Mitsukiyo.append("Future Bossa")
Mitsukiyo.append("Lemonade Diary")
Mitsukiyo.append("Morose Dreamer")
Mitsukiyo.append("Koi is love")
Mitsukiyo.append("Aira")
Mitsukiyo.append("Guruguru Usagi")
Mitsukiyo.append("Coffee Cats")
Mitsukiyo.append("Rolling Beat")
Mitsukiyo.append("Merry Blue")
Mitsukiyo.append("Blooming moon")
Mitsukiyo.append("Pixel Time")
Mitsukiyo.append("Virtual Storm Hard Arrange")
Mitsukiyo.append("Snow Pantomime")
Mitsukiyo.append("Interface Hard Arrange")
Mitsukiyo.append("Burning Love")
Mitsukiyo.append("Summer Bounce")
Mitsukiyo.append("Colorful Beach")
Mitsukiyo.append("Hifumi Daisuki")
Mitsukiyo.append("PRST Academy")
Mitsukiyo.append("PRST Marching")
Mitsukiyo.append("Summertime archive")
Mitsukiyo.append("Constant Moderato -Piano Arrange-")
Mitsukiyo.append("Formless Dream")
Mitsukiyo.append("Bunny Bunny Carrot Carrot")
Mitsukiyo.append("Blue New Year!")
Mitsukiyo.append("Nesno wons")