Nor: list = []

Nor.append("Midnight Trip (Short)")
Nor.append("Daily Routine 247")
Nor.append("Hello to Halo")
Nor.append("GGF")
Nor.append("Vivid Night")
Nor.append("Aoharu")
Nor.append("Aoharu (short)")
Nor.append("Walkthrough")
Nor.append("Signal of Abydos")
Nor.append("Sugar story")
Nor.append("ARES")
Nor.append("Vibes")
Nor.append("Future Lab")
Nor.append("After the Beep")
Nor.append("Moment")
Nor.append("Fearful Utopia")
Nor.append("Han-nari")
Nor.append("SAKURA PUNCH")
Nor.append("RE Aoharu")
Nor.append("RE Aoharu (Short)")
Nor.append("RE Aoharu (Title)")
Nor.append("SAKURA PUNCH Hard Arrange")
Nor.append("FEEEEVER TIME")
Nor.append("Crucial Issue")
Nor.append("OperationD")